/** Social auth actions */
export const GET_ORDERS_COUNT_LOADING = 'GET_ORDERS_COUNT_LOADING';
export const GET_ORDERS_COUNT_SUCCESS = 'GET_ORDERS_COUNT_SUCCESS';
export const GET_ORDERS_COUNT_FAIL = 'GET_ORDERS_COUNT_FAIL';
