/** Social auth actions */
export const GET_USER_BALANCE_LOADING = 'GET_USER_BALANCE_LOADING';
export const GET_USER_BALANCE_SUCCESS = 'GET_USER_BALANCE_SUCCESS';
export const GET_USER_BALANCE_FAIL = 'GET_USER_BALANCE_FAIL';
